Courses data model with validations
teamdotjs/v2 pull request #198
Opened 2017-02-23 04:29 UTC by mwitte98

Related Issue #176 

Changes:
- Courses data model with validations
  - Lesson can't be in a course twice
  - Course instructor can only add the lessons they own
  - Student can't be in a course twice
  - Student can't be in a course they're the instructor for

2017-02-23 20:36 UTC, djrenren requested changes

2017-02-23 20:36 UTC, djrenren commented on app/models/course_lesson.rb
> +class CourseLesson < ApplicationRecord
Couldn't we just put `belongs_to :course, optional: true, class_name: 'Course'` on `Lesson` and skip this entire join table? seeing as a lesson can only be in one Course.

2017-02-23 20:36 UTC, djrenren commented on app/models/course_student.rb
> +class CourseStudent < ApplicationRecord
We should probably add a `has_many`...`through` to user so we can access courses that way.

2017-02-23 21:34 UTC, mwitte98 commented on app/models/course_student.rb
> +class CourseStudent < ApplicationRecord
Yeah forgot about that...will do

2017-02-24 01:39 UTC, mwitte98 commented
Updated to access courses from lesson and user

2017-02-24 18:54 UTC, djrenren commented
Please update the seed so we have a sample. otherwise looks good

2017-02-24 19:02 UTC, mwitte98 commented
@djrenren updated seed

2017-02-24 19:33 UTC, djrenren commented
Sorry for being an asshole but can we put a lesson in it too? Maybe just a copy of A's.

2017-02-24 19:40 UTC, mwitte98 commented
@djrenren no problem. Done.

2017-02-24 19:51 UTC, djrenren approved these changes

2017-02-24 20:27 UTC, merged