Show Practice create errors on practice view
teamdotjs/v2 pull request #204
Opened 2017-02-28 16:26 UTC by 7imbrook

Changes:
- adds pinning to error reducer

2017-02-28 16:40 UTC, mwitte98 requested changes

2017-02-28 16:40 UTC, mwitte98 commented on app/models/wordinfo.rb
> +    wordinfos&['context_sentence']&.map! { |ct| ct['context_sentence'] }
Please change syntax to `wordinfos&.[]('')` and undo changes on lines 18-27

2017-02-28 16:40 UTC, mwitte98 commented on client/src/actions/practice.ts
> +            console.log(err);
console.log

2017-02-28 16:53 UTC, 7imbrook commented on app/models/wordinfo.rb
> +    wordinfos&['context_sentence']&.map! { |ct| ct['context_sentence'] }
I'm really not sure what's suppose to be here, can you just push it up to my branch. It was a merge conflict

2017-02-28 17:19 UTC, mwitte98 commented on app/models/wordinfo.rb
> +    wordinfos&['context_sentence']&.map! { |ct| ct['context_sentence'] }
Done

2017-02-28 19:29 UTC, mwitte98 commented
@7imbrook I just remembered that the reason why I kept wordinfo sentences formatted as `[{context_sentence: ''}]` and not an array of strings is to support primary and secondary sentences. I know it's not on the short term roadmap, but we should leave it as it is now so we don't have to change it back to an array of objects later.

2017-02-28 20:13 UTC, djrenren commented
Couldn't we just use a different context sentence?

2017-02-28 20:35 UTC, mwitte98 commented
We could. But we wanted all students to get the same sentence/questions when quizzed for fairness

2017-02-28 20:40 UTC, djrenren commented
Yeah alternates need to be the same on the question model but we don't need
them to be explicitly called out in the lesson

On Tue, Feb 28, 2017, 3:36 PM Matthew Witte <notifications@github.com>
wrote:

> We could. But we wanted all students to get the same sentence/questions
> when quizzed for fairness
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/teamdotjs/v2/pull/204#issuecomment-283153123>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAmvKhI8D6WmY9w9GpI9CmX2brnQA18Vks5rhIUegaJpZM4MOnMO>
> .
>

2017-02-28 21:25 UTC, mwitte98 commented
Okay, I can see how that would work. I'll need to complete #205 first before merging this PR since those are the tests that are failing.

2017-03-01 00:33 UTC, mwitte98 commented
Removed the changes to the 2 ruby files in this PR since I changed sentences to an array of strings throughout in #206

2017-03-01 19:28 UTC, mwitte98 approved these changes

2017-03-23 15:07 UTC, merged