Add part of speech to word editor
teamdotjs/v2 pull request #233
Opened 2017-03-28 19:20 UTC by mwitte98

Related Issue #222 

Changes:
- Add part of speech to word editor

2017-03-28 20:23 UTC, djrenren requested changes

2017-03-28 20:23 UTC, djrenren commented on client/src/reducers/lessonReducer.ts
> +export const parts_of_speech = ['noun', 'verb', 'adjective', 'adverb'];
This is not a large enough list.
You should consolidate with: https://github.com/teamdotjs/v2/blob/master/client/src/components/Lesson/WordCreator/WordFormSelector.tsx#L19

2017-03-28 20:25 UTC, mwitte98 commented on client/src/reducers/lessonReducer.ts
> +export const parts_of_speech = ['noun', 'verb', 'adjective', 'adverb'];
He mentioned in the meeting that he only uses those 4, that's why I removed the rest. Do we still want all of them anyways even if most won't ever be used?

2017-03-29 02:16 UTC, mwitte98 commented
@djrenren updated the change method and the type for parts of speech based on our discussion during the meeting

2017-04-04 20:23 UTC, djrenren approved these changes

2017-04-04 20:40 UTC, merged