Djrenren/courses ui
teamdotjs/v2 pull request #264
Opened 2017-04-14 18:28 UTC by djrenren

This implements the Course List -> Course/Lesson List -> Lesson Heirarchy. Still waiting on @mwitte98  for a way to create lessons inside a course, but the rest is up for review.

2017-04-14 19:27 UTC, mwitte98 commented on client/src/components/Home.tsx
>      onCreateLessonClick?: () => void;
Do we still need lessons, LessonSummary, and onCreateLessonClick in the home component?

2017-04-17 15:56 UTC, djrenren commented on client/src/components/Home.tsx
>      onCreateLessonClick?: () => void;
Nope

2017-04-18 14:03 UTC, mwitte98 commented on client/src/components/Home.tsx
>      onCreateLessonClick?: () => void;
Can you remove them? Looks good after that

2017-04-18 14:06 UTC, mwitte98 requested changes

2017-04-18 14:06 UTC, mwitte98 commented on client/src/containers/CourseContainer.tsx
> +export default LessonCreatorContainer;
Also rename this to CourseContainer

2017-04-18 19:10 UTC, mwitte98 approved these changes

2017-04-18 19:15 UTC, merged