Grades views
teamdotjs/v2 pull request #271
Opened 2017-05-01 03:18 UTC by mwitte98

Related Issue #28 

Changes:
- Grades views displaying your own grades and course grades for instructors

2017-05-01 22:36 UTC, djrenren requested changes
Just the one feedback. otherwise looks good.

2017-05-01 22:36 UTC, djrenren commented on client/src/components/AppBarRight.tsx
> +    handleGradesClose = () => {
This is the same function as handleLogoutClose and presumably always would be. Any chance we can redo the semantic and just handleMenuClose?

2017-05-02 01:02 UTC, mwitte98 commented
@djrenren I wanted to combine those methods initially but couldn't figure out how to. Finally found a way that works. I improved backend performance as well.

2017-05-02 01:35 UTC, djrenren approved these changes
B-E-A-UTIFUL

2017-05-02 01:36 UTC, merged