Add 409 status for errors when creating a user
teamdotjs/v2 pull request #52
Opened 2016-10-05 18:23 UTC by mwitte98

Related Issue #51

2016-10-05 18:57 UTC, 7imbrook requested changes

2016-10-05 18:57 UTC, 7imbrook commented on app/controllers/users_controller.rb
> +      render json: { errors: user.errors.full_messages }, status: :conflict
Can we actually check if there's a conflict for this? And not just assume its in the email

2016-10-05 22:58 UTC, mwitte98 commented on app/controllers/users_controller.rb
> +      render json: { errors: user.errors.full_messages }, status: :conflict
Do you want a 409 http status for email conflicts and a 400 http status for all other errors?

2016-10-06 01:17 UTC, 7imbrook commented on app/controllers/users_controller.rb
> +      render json: { errors: user.errors.full_messages }, status: :conflict
https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

2016-10-06 05:19 UTC, mwitte98 commented on app/controllers/users_controller.rb
> +      render json: { errors: user.errors.full_messages }, status: :conflict
#55 will have to be completed before I can continue with this. Any changes will break the build due to rubocop

2016-10-06 06:05 UTC, mwitte98 commented
This will break the build but once #59 is merged with it, it'll be fixed

2016-10-06 21:21 UTC, 7imbrook approved these changes

2016-10-06 21:27 UTC, merged