Add birthday with validations to user model
teamdotjs/v2 pull request #60
Opened 2016-10-06 08:34 UTC by mwitte98

Related Issue #57 

Changes:
- Adds birthday with validations to user model
- Fixes duplicate error message if password is blank

Breaking Changes:
- Build will fail until #59 is merged

2016-10-06 21:18 UTC, 7imbrook approved these changes

2016-10-06 21:22 UTC, 7imbrook requested changes
I'll send in an ISO format string

2016-10-11 14:50 UTC, djrenren commented
The string should be `ISO-8601` because this is the result of `(new Date()).toISOString()` in javascript. All indications are that rails will just handle this.

2016-10-11 16:32 UTC, 7imbrook approved these changes
I'd move the birthday year out into a constant or in a config, but other then that LGTM

2016-10-11 17:07 UTC, merged