Lessons are listed
teamdotjs/v2 pull request #87
Opened 2016-10-19 00:36 UTC by 7imbrook

Related Issue #84 

Changes:
- Lessons are listed on the homepage\

2016-10-23 20:36 UTC, 7imbrook commented
@teamdotjs/maintainers

2016-10-23 20:54 UTC, djrenren requested changes

2016-10-23 20:54 UTC, djrenren commented on client/src/components/Home.tsx
> +                    props.onClickLesson(parseInt(l.id)) :
If lesson id's are numbers, we should just make them numbers in our type.

2016-10-23 21:25 UTC, 7imbrook commented on client/src/components/Home.tsx
> +                    props.onClickLesson(parseInt(l.id)) :
the prop type always comes in as a string, so we have to parse it anyway, it is a number on the type.

2016-10-24 14:00 UTC, djrenren commented on client/src/components/Home.tsx
> +                    props.onClickLesson(parseInt(l.id)) :
But the id isn't on a prop. it's nested in an object.

2016-10-25 03:36 UTC, djrenren approved these changes

2016-10-25 17:10 UTC, merged